version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: inicio1234
      MYSQL_DATABASE: bd1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
